(0.000) SELECT "fly_flysaying"."id", "fly_flysaying"."content" FROM "fly_flysaying"  LIMIT 21; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "fly_flysaying"."id", "fly_flysaying"."content" FROM "fly_flysaying"  LIMIT 21; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
(0.000) SELECT "fly_flysaying"."id", "fly_flysaying"."content" FROM "fly_flysaying"; args=()
Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000002CEB37C7400>}
Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000002CEB37C7400>}
Exception while resolving variable 'rows' in template 'rest_framework/horizontal/textarea.html'.
Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\h5435\Drone\python_Drone\django-react-venv\lib\site-packages\django\template\base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [rows] in {'base_template': 'textarea.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000002CEB37C7400>}
"GET /api/flysaying/ HTTP/1.1" 200 8842
(0.000) SELECT "fly_flysaying"."id", "fly_flysaying"."content" FROM "fly_flysaying"  LIMIT 21; args=()
(0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
